### PR TITLE
Fix jQuery import.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Fixes an incorrect import of jQuery introduced in https://github.com/woocommerce/woocommerce-accommodation-bookings/commit/897c48ea329390d3321eeccbf475851406454338.

Closes https://linear.app/a8c/issue/WOOACBK-65/typeerror-jquery-error-when-creating-a-product

### Steps to test the changes in this Pull Request:

1. Activate Bookings and Bookings Availability
2. Navigate to the New Product screen
3. On trunk you will see `writepanel.js` throw a console error that jQuery is not defined -- the full error should be that `Uncaught TypeError: jquery__WEBPACK_IMPORTED_MODULE_0__.jQuery is not a function` in Firefox, similar in other browsers.
4. On this branch, no such error should occur

### Changelog entry

> Fix - JavasScript error reference to jQuery on New Product page.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Status-** Approved ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.9.0
* Theme:  
  - Twenty Twenty-Five Version: 1.4
* WooCommerce - Version 10.4.0 beta
* PHP: 8.3.0
* Web Server: Nginx
* Browser: Chrome - Version 143
* OS: macOS Sonoma 14.6.1 

</Details>


**Test Results -**  Issue has been fixed and accommodation booking product creation flow works as expected. 

**Functional Demo /  Screencast -**

Before Fix:

Screenshot 2025-12-10 at 8 08 50 PM


After Fix: 

Screenshot 2025-12-10 at 8 09 04 PM

**Review by ankitguptaindia — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.9
- Theme: Twenty Twenty-Five 1.4
- WooCommerce - 10.4.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀
